#!/bin/bash
# provision-gym.sh <slug>
#
# Creates a fresh gym install at /var/www/<slug>.<BASE_DOMAIN>/:
#   - clones the repo
#   - creates an isolated MySQL database + user
#   - writes .env, runs composer install, imports schema
#   - sets up nginx vhost + SSL via certbot
#   - saves credentials to /etc/gym-deploy/credentials/<fqdn>.txt
#
# Config is loaded from /etc/gym-deploy.conf:
#   BASE_DOMAIN=yourdomain.com
#   REPO_URL=https://github.com/Darkened-Z/Gym-software.git
#   LETSENCRYPT_EMAIL=you@yourdomain.com
#   PHP_FPM_SOCK=/var/run/php/php8.2-fpm.sock
#   NGINX_VHOST_TEMPLATE=/etc/gym-deploy/nginx-vhost.conf.template
#
# Usage:  sudo provision-gym.sh ironhouse

set -euo pipefail

# ---- config ----
[ -f /etc/gym-deploy.conf ] && source /etc/gym-deploy.conf
: "${BASE_DOMAIN:?BASE_DOMAIN not set (configure /etc/gym-deploy.conf)}"
: "${REPO_URL:?REPO_URL not set (configure /etc/gym-deploy.conf)}"
: "${LETSENCRYPT_EMAIL:?LETSENCRYPT_EMAIL not set (configure /etc/gym-deploy.conf)}"
PHP_FPM_SOCK="${PHP_FPM_SOCK:-/var/run/php/php8.2-fpm.sock}"
NGINX_VHOST_TEMPLATE="${NGINX_VHOST_TEMPLATE:-/etc/gym-deploy/nginx-vhost.conf.template}"
DEFAULT_TIMEZONE="${DEFAULT_TIMEZONE:-Asia/Karachi}"

# ---- args ----
if [ $# -ne 1 ]; then
  echo "Usage: $0 <slug>" >&2
  echo "  slug: lowercase, alphanumeric or dashes (e.g. ironhouse, fit-zone-22)" >&2
  exit 1
fi

SLUG="$1"
if ! [[ "$SLUG" =~ ^[a-z0-9-]+$ ]]; then
  echo "ERROR: slug must be lowercase letters, digits or dashes only." >&2
  exit 1
fi

FQDN="${SLUG}.${BASE_DOMAIN}"
INSTALL_DIR="/var/www/${FQDN}"
DB_NAME="gym_${SLUG//-/_}"
DB_USER="$DB_NAME"
DB_PASS="$(openssl rand -base64 24 | tr -d '/+=')"

if [ -d "$INSTALL_DIR" ]; then
  echo "ERROR: ${INSTALL_DIR} already exists. Use deprovision-gym.sh first." >&2
  exit 1
fi

if [ ! -r "$NGINX_VHOST_TEMPLATE" ]; then
  echo "ERROR: nginx vhost template not found at ${NGINX_VHOST_TEMPLATE}" >&2
  exit 1
fi

echo "→ Provisioning ${FQDN}"
echo "  Install dir: ${INSTALL_DIR}"
echo "  Database:    ${DB_NAME}"

# ---- 1. clone ----
echo "→ Cloning repo..."
git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"

# ---- 2. composer install ----
echo "→ composer install..."
( cd "$INSTALL_DIR" && composer install --no-dev --optimize-autoloader --no-interaction )

# ---- 3. create DB + user ----
echo "→ Creating database and user..."
mysql <<SQL
CREATE DATABASE \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

# ---- 4. import schema ----
echo "→ Importing schema..."
if [ -f "${INSTALL_DIR}/database/full_setup.sql" ]; then
  mysql "$DB_NAME" < "${INSTALL_DIR}/database/full_setup.sql"
else
  for sql in 01_schema.sql 02_seeds.sql 03_whatsapp_reminders.sql 04_payment_schema_compat.sql 05_whatsapp_automation.sql; do
    [ -f "${INSTALL_DIR}/database/${sql}" ] && mysql "$DB_NAME" < "${INSTALL_DIR}/database/${sql}"
  done
fi
# Supplemental indexes (legacy script). full_setup.sql / 01_schema.sql already
# define most indexes inline, so tolerate "Duplicate key name" while still
# applying any index the base schema is missing (e.g. attendance idx_date).
if [ -f "${INSTALL_DIR}/sql/add_indexes.sql" ]; then
  echo "→ Applying supplemental indexes (tolerating already-present)..."
  mysql --force "$DB_NAME" < "${INSTALL_DIR}/sql/add_indexes.sql" 2>&1 \
    | grep -vi 'duplicate key name' || true
fi

# ---- 5. write .env ----
echo "→ Writing .env..."
cat > "${INSTALL_DIR}/.env" <<ENV
# Auto-generated by provision-gym.sh on $(date -Iseconds)
DB_HOST=localhost
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASS}

APP_ENV=production
APP_DEBUG=false
APP_TIMEZONE=${DEFAULT_TIMEZONE}

SESSION_SECURE_COOKIE=true
SESSION_HTTPONLY=true
SESSION_SAMESITE=Strict
ENV
chmod 640 "${INSTALL_DIR}/.env"

# ---- 6. permissions ----
echo "→ Setting permissions..."
mkdir -p "${INSTALL_DIR}/uploads/profiles" "${INSTALL_DIR}/uploads/imports" "${INSTALL_DIR}/logs"
chown -R www-data:www-data "${INSTALL_DIR}"
chmod -R 0775 "${INSTALL_DIR}/uploads" "${INSTALL_DIR}/logs"

# ---- 7. nginx vhost (HTTP only first, so certbot can validate) ----
echo "→ Installing nginx vhost..."
VHOST_FILE="/etc/nginx/sites-available/${FQDN}.conf"
sed \
  -e "s|__SUBDOMAIN__|${FQDN}|g" \
  -e "s|__INSTALL_DIR__|${INSTALL_DIR}|g" \
  -e "s|__PHP_FPM_SOCK__|${PHP_FPM_SOCK}|g" \
  "$NGINX_VHOST_TEMPLATE" > "$VHOST_FILE"
ln -sf "$VHOST_FILE" "/etc/nginx/sites-enabled/${FQDN}.conf"
nginx -t
systemctl reload nginx

# ---- 8. SSL via certbot ----
echo "→ Requesting SSL certificate..."
if certbot --nginx -d "$FQDN" --non-interactive --agree-tos -m "$LETSENCRYPT_EMAIL" --redirect; then
  echo "  ✓ SSL active"
else
  echo "  ⚠ Certbot failed — site is HTTP-only for now. Run later:"
  echo "    sudo certbot --nginx -d ${FQDN}"
fi

# ---- 9. save credentials ----
mkdir -p /etc/gym-deploy/credentials
CREDS_FILE="/etc/gym-deploy/credentials/${FQDN}.txt"
cat > "$CREDS_FILE" <<CREDS
Gym slug:    ${SLUG}
URL:         https://${FQDN}
Install dir: ${INSTALL_DIR}
DB name:     ${DB_NAME}
DB user:     ${DB_USER}
DB password: ${DB_PASS}
Created:     $(date -Iseconds)

NEXT STEPS
----------
1. Open https://${FQDN}/setup.php   (one-time license activation)
2. Log in to https://${FQDN}/       as admin / admin123
3. Change the admin password IMMEDIATELY (Settings → Change password)
4. Optional branding: edit ${INSTALL_DIR}/assets/css/style.css
   and replace ${INSTALL_DIR}/assets/images/logo.png
CREDS
chmod 600 "$CREDS_FILE"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✓ Provisioned: https://${FQDN}"
echo "  ✓ Credentials saved: ${CREDS_FILE}"
echo ""
echo "  NEXT: visit https://${FQDN}/setup.php to activate"
echo "════════════════════════════════════════════════════════════════"
